const tableData = [
    {
        "id": 1,
        "first_name": "Brynne",
        "last_name": "Lusgdin",
        "email": "blusgdin0@ebay.com",
        "gender": "Female",
        "ip_address": "62.70.143.146"
    }, {
        "id": 2,
        "first_name": "Noble",
        "last_name": "Backshill",
        "email": "nbackshill1@amazon.co.uk",
        "gender": "Male",
        "ip_address": "138.166.51.56"
    }, {
        "id": 3,
        "first_name": "Kalila",
        "last_name": "Manders",
        "email": "kmanders2@1und1.de",
        "gender": "Female",
        "ip_address": "31.12.47.88"
    }, {
        "id": 4,
        "first_name": "Baryram",
        "last_name": "Winterscale",
        "email": "bwinterscale3@unblog.fr",
        "gender": "Male",
        "ip_address": "164.72.161.156"
    }, {
        "id": 5,
        "first_name": "Vladamir",
        "last_name": "Pratley",
        "email": "vpratley4@bandcamp.com",
        "gender": "Male",
        "ip_address": "160.170.26.114"
    }, {
        "id": 6,
        "first_name": "Marvin",
        "last_name": "Hendriks",
        "email": "mhendriks5@ask.com",
        "gender": "Male",
        "ip_address": "170.171.169.200"
    }, {
        "id": 7,
        "first_name": "Antin",
        "last_name": "Carville",
        "email": "acarville6@t-online.de",
        "gender": "Male",
        "ip_address": "38.189.239.214"
    }, {
        "id": 8,
        "first_name": "Renaldo",
        "last_name": "Beckham",
        "email": "rbeckham7@adobe.com",
        "gender": "Male",
        "ip_address": "252.13.13.92"
    }, {
        "id": 9,
        "first_name": "Udell",
        "last_name": "McSparran",
        "email": "umcsparran8@nasa.gov",
        "gender": "Male",
        "ip_address": "201.192.80.207"
    }, {
        "id": 10,
        "first_name": "Lyndel",
        "last_name": "Westrey",
        "email": "lwestrey9@dailymail.co.uk",
        "gender": "Female",
        "ip_address": "65.73.108.107"
    }
]

export default tableData;